# Generated by Django 6.0.2 on 2026-02-10 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200, verbose_name='Tytuł awarii')),
                ('opis', models.TextField(verbose_name='Opis awarii')),
                ('kategoria', models.CharField(choices=[('sprzet', 'Sprzęt'), ('oprogramowanie', 'Oprogramowanie'), ('net', 'Internet')], default='sprzet', max_length=20)),
                ('priorytet', models.CharField(choices=[('niski', 'Niski'), ('wysoki', 'Wysoki')], default='niski', max_length=20)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('w_trakcie', 'W trakcie'), ('zamkniete', 'Zamknięte')], default='nowe', max_length=20)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
            },
        ),
    ]
