# Generated by Django 6.0.2 on 2026-02-15 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={},
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='zgloszenia.zgloszenie')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('numer_seryjny', models.CharField(max_length=50, unique=True)),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zasoby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='urzadzenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zgloszenia.sprzet'),
        ),
    ]
