# Generated by Django 6.0.2 on 2026-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0002_alter_zgloszenie_options_komentarz_sprzet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshoty/', verbose_name='Zrzut ekranu (opcjonalnie)'),
        ),
    ]
