# Generated by Django 6.0.2 on 2026-02-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0003_zgloszenie_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshoty/'),
        ),
    ]
