# Generated by Django 6.0.2 on 2026-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zgloszenia', '0005_alter_komentarz_options_zgloszenie_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='data_rozwiazania',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data rozwiązania'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termin SLA'),
        ),
    ]
